# Generated by Django 4.2.11 on 2024-11-15 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oidc_provider', '0028_add_default_scope_20210503_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oidc_owned_clients', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='client',
            name='response_types',
            field=models.ManyToManyField(related_name='oidc_clients', to='oidc_provider.responsetype'),
        ),
        migrations.AlterField(
            model_name='client',
            name='scope',
            field=models.ManyToManyField(blank=True, default=None, help_text='Specifies the authorized scope values for the client app.', related_name='oidc_clients', to='oidc_provider.scope', verbose_name='Scopes'),
        ),
        migrations.AlterModelTable(
            name='client',
            table='oidc_provider_client',
        ),
    ]
